sartography/cr-connect-frontend

package-lock.json, package.json
Pointing shared libraries to version 277
=> Bumping up shared libraries version

package-lock.json, package.json, src/app/workflow/workflow.component.html, src/app/workflow/workflow.component.spec.ts, src/app/workflow/workflow.component.ts
Pretty much does what the ticket says - changes name of 'Continue' button to 'Acknowledge' when it is a MANUAL_TASK and there is only one of them
=> 218 change manual task button

e2e/tsconfig.json, package-lock.json, package.json, src/app/_interfaces/file-groupings.ts, src/app/workflow-files/workflow-files.component.html, src/app/workflow-files/workflow-files.component.scss, src/app/workflow-files/workflow-files.component.spec.ts, src/app/workflow-files/workflow-files.component.ts, src/app/workflow/workflow.component.html, src/app/workflow/workflow.component.spec.ts, src/app/workflow/workflow.component.ts, tsconfig.json
- requires cr-connect-workflow branch 277-document-pane-changes
Will likely require some cosmetic UI tweaks - please see commit for further comments #277
=> ticket #277 document pane changes

package-lock.json, package.json, src/app/workflow-files/workflow-files.component.html, src/app/workflow-files/workflow-files.component.ts, src/app/workflow-form/workflow-form.component.html, src/app/workflow-form/workflow-form.component.ts
Respect looping tasks, and allow for something to repeat until requested to save and move on.
=> Display metadata about files in the workflow-files display panel.

src/app/workflow-reset-dialog/workflow-reset-dialog.component.html, src/app/workflow-reset-dialog/workflow-reset-dialog.component.spec.ts, src/app/workflow-reset-dialog/workflow-reset-dialog.component.ts
well just a frontend fix, if you clear all info,  you now clear all docs
=> Fixes #471 - Clearing data should also clear documents

src/app/studies-dashboard/studies-dashboard.component.scss
its just css changes. makes approvals box fatter and removes extra space below 'Approvals'
=> make the approvals box more beauty-full

src/app/workflow/workflow.component.html
i dont know why i put this on its own branch to be honest
=> Fixes #525 - Change End Event button label

src/app/studies-dashboard/studies-dashboard.component.html, src/app/studies-dashboard/studies-dashboard.component.scss, src/app/studies-dashboard/studies-dashboard.component.spec.ts, src/app/studies-dashboard/studies-dashboard.component.ts
my own CUSTOM material search input that searches on id or study title or short name. And a test that actually works
=> Fixes #532 - Add Study Search capability to Main Dashboard

src/app/study/study.component.html
puts it short title when you have it
=> Fixes #538- Full Study Title not displaying if Short Title hasnt ben set

src/app/study/study.component.ts
=> Fixes #539 - Incorrect Personnel being displayed for PI

src/app/workflow/workflow.component.html
=> Another possible fix for this?

src/app/studies-dashboard/studies-dashboard.component.ts
=> Fixes #575- Reset Study not working

package-lock.json, package.json
See the shared libraries, if that is good, this should be good.
=> Bumping for validation fixes in shared libraries.

src/app/studies-dashboard/studies-dashboard.component.html, src/app/studies-dashboard/studies-dashboard.component.ts
Add Study ID to Approvals Panel
=> Approval panel update #701

src/app/document-history/document-history.component.html, src/app/document-history/document-history.component.ts
make sure we have the datasource before processing
=> document history bug fix

src/app/studies-dashboard/studies-dashboard.component.html
Use progress_status, instead of irb_status
=> Progress status issue #721

src/app/studies-dashboard/studies-dashboard.component.html, src/app/studies-dashboard/studies-dashboard.component.ts
Minor changes to the Approval panel
=> Chore/approval panel #728

src/app/task-logs/task-logs.component.scss
=> Logging tab changes #683

src/app/nav-links/nav-links.component.html, src/app/nav-links/nav-links.component.ts, src/app/navbar/navbar.component.html
Provide an easy way to "view as yourself" when you are viewing as someone else.
=> Chore/view as yourself #756

src/app/studies-dashboard/studies-dashboard.component.html, src/app/studies-dashboard/studies-dashboard.component.ts
Remove the main dashboard progress bar
=> Bug/dashboard progress #748
